# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
t_rand = torch.rand(7, 7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
t_rand2 = torch.rand(1, 7)
# Perform matrix multiplication
torch.matmul(t_rand, t_rand2.T)

tensor([[1.2144],
        [1.1162],
        [1.0027],
        [0.7490],
        [0.9426],
        [1.2706],
        [1.2173]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
#torch.random.manual_seed(seed = RANDOM_SEED)
torch.manual_seed(seed = RANDOM_SEED)
t_rand3 = torch.rand(7, 7)

#torch.random.manual_seed(seed = RANDOM_SEED)
torch.manual_seed(seed = RANDOM_SEED)
t_rand4 = torch.rand(1, 7)

# Matrix multiply tensors
matmul = torch.matmul(t_rand3, t_rand4.T)
print(f"{matmul} \n {matmul.shape}")

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]) 
 torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
RANDOM_SEED_CUDA = 1234



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
RANDOM_SEED_CUDA = 1234
torch.cuda.manual_seed(RANDOM_SEED_CUDA)
# Check for access to GPU
if torch.cuda.is_available():
  # Create two random tensors on GPU
  torch.cuda.manual_seed(RANDOM_SEED_CUDA)
  device = "cuda"
else:
  device = "cpu"
print(device)
tensor_r1 = torch.rand((2, 3), device = device)
tensor_r2 = torch.rand((2, 3), device = device)
print(f"{tensor_r1} \n {tensor_r2}")

cpu
tensor([[0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223]]) 
 tensor([[0.1689, 0.2939, 0.5185],
        [0.6977, 0.8000, 0.1610]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
matmul_cuda = torch.matmul(tensor_r1, tensor_r2.T)
matmul_cuda

tensor([[0.6131, 1.0917],
        [0.1886, 0.5684]])

In [8]:
matmul_cuda[1]

tensor([0.1886, 0.5684])

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
print(matmul_cuda.max())
# Find min
print(matmul_cuda.min())

tensor(1.0917)
tensor(0.1886)


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
print(matmul_cuda.argmax())

# Find arg min
print(matmul_cuda.argmin())

tensor(1)
tensor(2)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
torch.manual_seed(seed = RANDOM_SEED)
rand = torch.rand(1, 1, 1, 10)
print(rand.shape)
# Remove single dimensions
x = rand.squeeze()
print(x.shape)
# Print out tensors and their shapes


torch.Size([1, 1, 1, 10])
torch.Size([10])


In [12]:
t = torch.rand((1, 2), device = "gpu")

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: gpu