In [32]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Creating Tensors

In [33]:
# scalar
scalar = torch.tensor(7)
scalar

# dimension
print(scalar.ndim)
# Get tensor back as Python int
print(scalar.item())

0
7


In [34]:
# vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [35]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [8, 9]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX[0], "\n",MATRIX[1])

tensor([[7, 8],
        [8, 9]])
2
tensor([7, 8]) 
 tensor([8, 9])


In [36]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR.shape)

print(TENSOR[0],
      "\n",
      TENSOR[0, 0],
      "\n",
      TENSOR[0, 1],
      "\n",
      TENSOR[0, 2])

torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 
 tensor([1, 2, 3]) 
 tensor([4, 5, 6]) 
 tensor([7, 8, 9])


# 2)

## random Tensors

In [38]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6110, 0.7633, 0.4888, 0.1192],
        [0.4406, 0.2076, 0.6831, 0.9153],
        [0.5690, 0.8338, 0.0189, 0.3170]])

In [40]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #hight, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [42]:
zeros = torch.zeros(3, 4)
ones = torch.ones(3, 4)

In [43]:
print(zeros * random_tensor)
print(ones * random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.6110, 0.7633, 0.4888, 0.1192],
        [0.4406, 0.2076, 0.6831, 0.9153],
        [0.5690, 0.8338, 0.0189, 0.3170]])


In [44]:
ones.dtype

torch.float32

# Creating range of tensors and tensors-like

In [51]:
# Use torch.range()
one_to_ten = torch.arange(1, 11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [61]:
# FLoat32 tensor
float_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32,#dtype of tensor (float16/32 etc)
                            device="cpu",
                            requires_grad= False)
float_tensor.dtype

torch.float32

In [62]:
float_16_tensor = float_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

# Tensor attributes

In [63]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7304, 0.3401, 0.1581, 0.6801],
        [0.6731, 0.7533, 0.5920, 0.9875],
        [0.4229, 0.7354, 0.7124, 0.6720]])

In [66]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.7304, 0.3401, 0.1581, 0.6801],
        [0.6731, 0.7533, 0.5920, 0.9875],
        [0.4229, 0.7354, 0.7124, 0.6720]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Tensor Operations

In [72]:
# Addition/Subtraction
# Multiplication (element-wise)
# Division
# Matrix multiplication

tensor = torch.tensor([1, 2, 3])

print(tensor + 10)
print(tensor * 10)
print(tensor - 10)
print(tensor/10)
# in build functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])
tensor([10, 20, 30])
tensor([11, 12, 13])


In [75]:
tensor2 = torch.tensor([1, 2, 3])
print(torch.matmul(tensor, tensor2))
tensor3 = torch.rand([3, 4])
tensor4 = torch.rand([4, 3])
print(torch.matmul(tensor3, tensor4))

tensor(14)
tensor([[0.6873, 0.4492, 0.8824],
        [1.8372, 1.0355, 1.2824],
        [1.4995, 0.8266, 1.0589]])


# Transpose

In [80]:
tensor_t = torch.tensor([[1, 1, 1],
                         [2, 2, 2],
                         [3, 3, 3]])
tensor_t

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [81]:
tensor_t.T

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

# Tensor min, max, mean, sum, etc

In [85]:
torch.max(tensor_t), tensor_t.max()

(tensor(3), tensor(3))

In [86]:
torch.min(tensor_t), tensor_t.min()

(tensor(1), tensor(1))

In [93]:
print(torch.mean(tensor_t.type(torch.float32)))
print(torch.mean(tensor_t.type(torch.float32).mean()))

tensor(2.)
tensor(2.)


In [95]:
torch.sum(tensor_t), tensor_t.sum()

(tensor(18), tensor(18))

In [97]:
print(tensor_t.argmax(), tensor_t.argmin())

tensor(6) tensor(0)
